# azure-pipelines.yml

trigger:
  branches:
    include:
      - api_basic

pool:
  vmImage: ubuntu-latest

steps:
  # Explicitly checkout the code with full depth (if needed)
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true  # if you need access to other repositories or artifacts
    fetchDepth: 0  # Setting to 0 for full depth, change as per your requirements

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npx playwright install
      npx playwright test
    displayName: 'Install and Run Playwright Tests'
